# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }


Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
  Exclude:
    - "app/activities/rules/shift_validation/shift_rest_time_rule.rb"

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/AccessorGrouping:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: false

Rails/AfterCommitOverride:
  Enabled: false

Rails/FindById:
  Enabled: false

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: false

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/WhereExists:
  Enabled: false

Rails/WhereNot:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - "bin/*"

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    - "bin/*"
    - "config/initializers/carrierwave.rb"

Rails/SkipsModelValidations:
  Enabled: false

Layout/EmptyLines:
  Enabled: true

Rails/FilePath:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - "app/controllers/gruf/grpc/**/*.rb"

Naming/VariableNumber:
  CheckSymbols: false

Lint/MissingSuper:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConcurrentMonotonicTime:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/MapMethodChain:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true

Performance/RedundantEqualityComparisonBlock:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringBytesize:
  Enabled: true

Performance/StringIdentifierArgument:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: false

AllCops:
  NewCops: enable

plugins:
  - rubocop-obsession
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - sevencop

Layout/ClassStructure:
  AutoCorrect: true
  Categories:
    association:
      - has_many
      - has_one
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    macros:
      - validates
      - validate
    module_inclusion:
      - include
      - prepend
      - extend
  Enabled:     true
  Severity:    warning
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - constants
    - private_attribute_macros
    - private_delegate
    - private_methods

Layout/ExtraSpacing:
  Enabled: true
  ForceEqualSignAlignment: false
  AllowForAlignment: true
Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
  EnforcedColonStyle:
    - key
Layout/MultilineHashKeyLineBreaks: { Enabled: true, AutoCorrect: false}
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: always

Sevencop/MethodDefinitionArgumentsMultiline:     { Enabled: false }
Sevencop/MethodDefinitionInIncluded:             { Enabled: true }
Sevencop/MethodDefinitionKeywordArgumentOrdered: { Enabled: true }
Sevencop/MethodDefinitionOrdered:                { Enabled: false }
Sevencop/RSpecDescribeHttpEndpoint:              { Enabled: true }
Sevencop/RSpecEmptyLineAfterLet:                 { Enabled: false }
Sevencop/RSpecExamplesInSameGroup:               { Enabled: true }
Sevencop/RSpecMatcherConsistentParentheses:      { Enabled: true }
Sevencop/RSpecMemoizedHelperBlockDelimiter:      { Enabled: false }
Sevencop/RSpecRailsStatusCodeCheckBySubject:     { Enabled: true }

Sevencop/HashElementOrdered:
  Enabled: true
  Safe: false
  Exclude:
    - config/routes.rb

Obsession/MethodOrder:                { Enabled: true, Severity: warning }
Obsession/Rails/MigrationBelongsTo:   { Enabled: true, Severity: warning, AutoCorrect: true }
Obsession/Rails/ServiceName:          { Enabled: false }
Obsession/Rails/ServicePerformMethod: { Enabled: false }
RSpec/AlignLeftLetBrace:              { Enabled: false}
RSpec/AlignRightLetBrace:             { Enabled: false}
RSpec/AnyInstance:                    { Enabled: true, Severity: warning }
RSpec/AroundBlock:                    { Enabled: true}
RSpec/ContextWording:                 { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/EmptyLineAfterFinalLet:         { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/EmptyLineAfterHook:             { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/EmptyLineAfterSubject:          { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/ExampleLength:                  { Enabled: false}
RSpec/ExampleWording:                 { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/ExpectChange:                   { Enabled: false}
RSpec/ExpectInHook:                   { Enabled: false }
RSpec/ImplicitSubject:                { Enabled: false}
RSpec/IndexedLet:                     { Enabled: false}
RSpec/LeadingSubject:                 { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/LetBeforeExamples:              { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/LetSetup:                       { Enabled: false}
RSpec/MatchArray:                     { Enabled: false}
RSpec/MessageSpies:                   { Enabled: false}
RSpec/MetadataStyle:                  { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/MultipleExpectations:           { Enabled: false}
RSpec/MultipleMemoizedHelpers:        { Enabled: false}
RSpec/NamedSubject:                   { Enabled: false}
RSpec/NestedGroups:                   { Enabled: false}
RSpec/PendingWithoutReason:           { Enabled: true, Severity: warning , AutoCorrect: false}
RSpec/ReceiveCounts:                  { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/ScatteredLet:                   { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/SortMetadata:                   { Enabled: true, AutoCorrect: true, Severity: warning }
RSpec/StubbedMock:                    { Enabled: false}
